(defvar unlogic-installed-packages
  '(
    aggressive-indent
    auto-complete
    color-theme-sanityinc-tomorrow
    dash
    elisp-slime-nav
    expand-region
    find-file-in-project
    goto-last-change
    helm
    helm-swoop
    highlight
    highlight-symbol
    htmlize
    ido-completing-read+
    ido-ubiquitous
    lua-mode
    openwith
    org
    paredit
    popup
    refheap
    s
    thesaurus
    xmlgen
    ))
