(defvar unlogic-installed-packages
  '(
    auto-complete
    clojure-mode
    color-theme-sanityinc-tomorrow
    dash
    elisp-slime-nav
    expand-region
    find-file-in-project
    gh
    gist
    goto-last-change
    helm
    htmlize
    idle-highlight-mode
    ido-ubiquitous
    javap-mode
    highlight-symbol
    key-chord
    legalese
    linum-relative
    logito
    lua-mode
    magit
    markdown-mode
    minimap
    mo-git-blame
    multiple-cursors
    openwith
    paredit
    pcache
    popup
    projectile
    refheap
    s
    smex
    starter-kit
    starter-kit-bindings
    starter-kit-eshell
    starter-kit-lisp
    sunrise-commander
    sunrise-x-checkpoints
    sunrise-x-loop
    sunrise-x-mirror
    thingatpt
    undo-tree
    xmlgen
    yasnippet-bundle
    ))
